/* ============================================================================
   PROJECT DATA  —  edit this file to change the dashboard. No code knowledge
   needed: each project is one { ... } block. Add, remove or reorder freely.

   ── CONTACTS ──────────────────────────────────────────────────────────────
   Each project routes its "Express interest" button to one contact below.
   Set a project's  contact:  field to one of the keys:  benjamin | matilda |
   irina | jonathan.  Benjamin is the default.

   ⚠  PLACEHOLDER EMAILS: only Benjamin's address is confirmed. Replace the
   matilda / irina / jonathan addresses with the real ones before going live.
   ========================================================================== */

window.CONTACTS = {
  benjamin: { name: "Benjamin Schmidt",  email: "benjamin.schmidt@pauseai.info" }, // confirmed
  matilda:  { name: "Matilda da Rue",    email: "matilda.darue@pauseai.info"   }, // ⚠ confirm address
  irina:    { name: "Irina Taverna",     email: "irina.taverna@pauseai.info"   }, // ⚠ confirm address
  jonathan: { name: "Jonathan Moody",    email: "jonathan.moody@pauseai.info"  }, // ⚠ confirm address
};

/* region:    "DE" | "Global" | "Both"
   expertise: "Beginner-friendly" | "Some experience" | "Specialist"          */

window.PROJECTS = [
  {
    title: "Replicate the professor appeal — your country",
    category: "Coalitions & Allies",
    region: "Both",
    effort: "40–60h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Run the 152-professor playbook in your country: adapt the appeal, recruit signatories, and time a delegation ask to a summit.",
    skills: ["Outreach", "Academic networks", "Writing", "Coordination"],
    detail: "The German appeal is a turnkey template. Localise the text, build a list of professors, send a tight email campaign, collect signatures, and coordinate a public ask to your national delegation — ideally timed to an international summit. The original wording, templates and lessons-learned are ready to hand off, so this costs a fraction of the original 100 hours.",
  },
  {
    title: "Cold outreach to Nobel laureates & top-prize honourees",
    category: "Coalitions & Allies",
    region: "Global",
    effort: "40–80h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Systematic outreach to the world's most credible scientists — living Nobel laureates and equivalents — inviting them to lend their name.",
    skills: ["Cold outreach", "Research", "Persuasive writing", "Tracking / CRM"],
    detail: "Build and work a master list of living Nobel laureates (Physics, Chemistry, Medicine, Economics, Peace, Literature) plus equivalent-caliber honours — the Fields Medal and Abel Prize in mathematics, the Turing Award as computing's 'Nobel', and comparable top prizes in other fields. A single high-prestige signatory can unlock press and political attention far out of proportion to the hours spent.",
  },
  {
    title: "Engage the national academies of science",
    category: "Coalitions & Allies",
    region: "Global",
    effort: "50–100h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Bring institutional bodies — Royal Society, Royal Society of Edinburgh, Leopoldina, US National Academy of Sciences — into the AI-safety conversation.",
    skills: ["Institutional outreach", "Policy literacy", "Diplomacy", "Writing"],
    detail: "Where individual laureates lend a name, academies lend an institution. Map the relevant bodies — the Royal Society (UK), the Royal Society of Edinburgh, the Leopoldina (Germany's national academy) and the US National Academy of Sciences — find the right committees and fellows, and make the case for statements, briefings or convenings on frontier-AI risk.",
  },
  {
    title: "Embed in the PauseAI communications team",
    category: "Media & Press",
    region: "Both",
    effort: "40–80h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Join the engine room: write newsletters built for translation across chapters, plus press releases and op-eds.",
    skills: ["Writing & editing", "Newsletters", "Press releases", "Multi-chapter coordination"],
    detail: "Become part of PauseAI's communications team. Write newsletters designed to be translated and reused by other national chapters, draft and place press releases, and co-author or ghost-write op-eds for credible voices. High-leverage for strong writers who want their words multiplied across countries.",
  },
  {
    title: "Write Pause-focused scenarios",
    category: "Culture & Reach",
    region: "Both",
    effort: "20h+ · scales with depth",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Sketch vivid, plausible Pause-focused scenarios of how the next years could unfold — in the spirit of AI 2027 and Europe 2031.",
    skills: ["Forecasting", "Narrative writing", "Strategy", "Research"],
    detail: "Write a Pause-focused scenario: a concrete, plausible narrative of how the coming years could play out and where the decisive intervention points lie. A lighter sketch can be done quickly; a richly researched, detailed version rewards much more time. Scenarios make abstract risk legible and give policymakers and the public a shared picture to act on. Use AI 2027 and Europe 2031 below as format references.",
    links: [
      { label: "AI 2027", url: "https://ai-2027.com" },
      { label: "Europe 2031", url: "https://europe2031.ai/" },
    ],
  },
  {
    title: "Place 1+ op-eds in German / other press",
    category: "Media & Press",
    region: "Both",
    effort: "60–100h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Place one or more op-eds in the German (or other) quality press by a credible voice — possibly anchored to a bigger project like a scientist appeal.",
    skills: ["Writing", "Media relationships", "Editing", "Sourcing authors"],
    detail: "Place at least one op-ed in the German or other quality press, authored by a credible voice. This can cooperate with another project — for instance using a bigger scientist appeal as the news hook / anchor — and builds lasting relationships with the editors who commission the pieces.",
  },
  {
    title: "Recruit a spokesperson bench & celebrities",
    category: "Coalitions & Allies",
    region: "Both",
    effort: "40–80h",
    expertise: "Specialist",
    contact: "benjamin",
    experimental: true,
    blurb: "Assemble a small roster of respected scientists, ex-officials, public figures and celebrities willing to lend their name and speak publicly.",
    skills: ["Relationship-building", "Vetting", "Coordination", "Persuasion"],
    detail: "Recruit a small, high-trust bench of respected scientists, former officials, public figures and celebrities willing to be named and to speak when needed. This is lasting institutional credibility — the asset every other campaign draws on.",
  },
  {
    title: "Cold outreach to journalists — build relationships & brief them",
    category: "Media & Press",
    region: "Both",
    effort: "30–60h",
    expertise: "Specialist",
    contact: "benjamin",
    experimental: true,
    blurb: "Cold-outreach to journalists to build lasting relationships and brief them, making PauseAI a trusted go-to source on AI risk.",
    skills: ["Media relations", "Cold outreach", "Briefing prep", "Discretion"],
    detail: "Reach out to tech- and policy reporters, build relationships over time, and brief them — on background or on the record — so that when an AI-risk story breaks, PauseAI is the trusted first call. Builds slowly but compounds: relationships become coverage.",
  },
  {
    title: "Labor-union engagement",
    category: "Coalitions & Allies",
    region: "Both",
    effort: "50–80h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Turn the 'labs are racing to automate every job' framing into a concrete union partnership — German unions like IG Metall and ver.di are just one example; this works internationally.",
    skills: ["Organizing", "Coalition-building", "Labor landscape", "Negotiation"],
    detail: "Translate the automation-of-work argument into a working partnership with unions, who bring organising muscle and political weight. German unions like IG Metall and ver.di are a natural starting point, but the same approach applies to unions internationally. A bridge from job-loss concern to the broader case about human disempowerment.",
  },
  {
    title: "Youth & future-generations campaign",
    category: "Outreach",
    region: "Both",
    effort: "40–80h",
    expertise: "Beginner-friendly",
    contact: "benjamin",
    blurb: "A youth-led 'right to a future' campaign framing frontier AI as intergenerational justice — school-strike energy, and engaging youth parliaments.",
    skills: ["Campaigning", "Social media", "Youth organizing", "Storytelling"],
    detail: "Build a youth-led campaign framing frontier AI as a question of intergenerational justice — a 'right to a future'. Borrows the moral clarity and energy of the climate school-strike movement, and can work through youth parliaments to reach decision-makers.",
  },
  {
    title: "Pause-minded think tank & bureaucracy engagement",
    category: "Policy & Legal",
    region: "DE",
    effort: "80–150h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Engage the civil service — harder to engage and move than politicians — and lay groundwork for a more pause-minded think tank.",
    skills: ["Policy analysis", "Institutional savvy", "Writing", "Networking"],
    detail: "Engage the ministerial bureaucracy, which is even harder to engage and move than elected politicians, and lay the groundwork for a more pause-minded think tank — giving the position a permanent institutional home and analytical heft.",
  },
  {
    title: "Find a legal argument for a Pause",
    category: "Policy & Legal",
    region: "Both",
    effort: "60–120h",
    expertise: "Specialist",
    contact: "benjamin",
    experimental: true,
    blurb: "Find — and act on — a legal argument for a Pause, exploring European law, the German Grundgesetz, and precedents like climate litigation.",
    skills: ["Constitutional law", "EU law", "Legal writing", "Argumentation"],
    detail: "Develop and then act on a legal argument for a Pause. Explore avenues across European law, the German Grundgesetz (e.g. Article 1 human dignity and the state's precautionary duties of protection), and precedents from other domains such as climate litigation. A novel legal hook for advocacy and potential litigation.",
  },
  {
    title: "Local-politician pledge campaign",
    category: "Outreach",
    region: "DE",
    effort: "20–40h",
    expertise: "Beginner-friendly",
    contact: "benjamin",
    blurb: "Get municipal and state-level politicians to sign a simple public pledge supporting international AI coordination.",
    skills: ["Outreach", "Local politics", "Follow-up", "Tracking"],
    detail: "Build a visible roster of support from the ground up by getting Kommunal- and Land-level politicians to sign a simple public pledge backing international AI coordination. Low barrier to entry, compounding visibility.",
  },
  {
    title: "Working with artists",
    category: "Culture & Reach",
    region: "Both",
    effort: "30–60h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Partner with artists to make AI risk resonate culturally, not just intellectually.",
    skills: ["Creative collaboration", "Curation", "Project management"],
    detail: "Collaborate with artists — visual, musical, performance — to create work that makes the stakes of frontier AI felt, reaching audiences that argument alone never will.",
  },
  {
    title: "Working with influencers",
    category: "Culture & Reach",
    region: "Both",
    effort: "30–60h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Engage online creators to carry AI-safety messages to large, non-policy audiences in their own voice.",
    skills: ["Creator relations", "Messaging", "Social media"],
    detail: "Identify and brief online creators whose audiences we don't otherwise reach, equipping them to talk about AI risk credibly and in their own voice — or, for example, invite PauseAI onto a podcast.",
  },
  {
    title: "Build a journalist coalition",
    category: "Media & Press",
    region: "Both",
    effort: "40–80h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Convene a coalition of journalists committed to sustained, serious AI-risk reporting.",
    skills: ["Media relations", "Coalition-building", "Coordination"],
    detail: "Convene and support a coalition of journalists committed to serious, sustained coverage of AI risk — shared resources, contacts and story leads that keep the issue in the news.",
  },
  {
    title: "Very targeted outreach to land a celebrity champion",
    category: "Culture & Reach",
    region: "Both",
    effort: "40–100h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Deep, high-touch outreach to recruit one prominent cultural or scientific figure as a visible public face. High upside; single-point-of-failure risk.",
    skills: ["High-stakes outreach", "Relationship-building", "Discretion"],
    detail: "Recruit a single prominent German cultural or scientific figure willing to be the visible face of the cause. Potentially transformative reach — but a concentrated dependency, so handle with care and a backup plan.",
  },
  {
    title: "Cold outreach to find celebrity champions",
    category: "Outreach",
    region: "Global",
    effort: "30–60h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Make landing a celebrity champion a numbers game: structured, international cold outreach at scale.",
    skills: ["Cold outreach", "Research", "Persistence", "Tracking"],
    detail: "Run a structured, international cold-outreach effort to find celebrity champions — researching candidates, finding routes to them, and making the ask at scale so that landing one becomes a numbers game rather than luck.",
  },
  {
    title: "Cold outreach to unions worldwide",
    category: "Outreach",
    region: "Global",
    effort: "30–60h",
    expertise: "Beginner-friendly",
    contact: "benjamin",
    blurb: "Extend the automation-and-disempowerment conversation to unions in multiple countries.",
    skills: ["Cold outreach", "Research", "Cross-cultural communication"],
    detail: "Extend union engagement beyond Germany: identify and contact unions in multiple countries, opening conversations about automation, worker power and the case for AI coordination.",
  },
  {
    title: "Cold outreach to churches & faith communities",
    category: "Outreach",
    region: "Global",
    effort: "30–60h",
    expertise: "Beginner-friendly",
    contact: "benjamin",
    blurb: "Reach faith communities across countries as moral-voice allies on human dignity and the future.",
    skills: ["Cold outreach", "Interfaith literacy", "Writing"],
    detail: "Reach out to churches and faith communities in different countries, who bring moral authority, organised membership and a long tradition of speaking on questions of human dignity and the future.",
  },
  {
    title: "Build a global coalition — a team effort (3+ fellows)",
    category: "Coalitions & Allies",
    region: "Global",
    effort: "Team · 3+ fellows",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Unite one constituency across countries — e.g. scientists or faith communities — into a single large international organisation, such as a global Scientists for a Pause.",
    skills: ["Coordination", "International organising", "Coalition-building", "Project management"],
    detail: "For three or more fellows working together. Take a single constituency — scientists, or church and faith communities, for example — and combine the national efforts from different countries into one big international organisation or group: a global 'Scientists for a Pause', or an international faith coalition. More ambitious than any single national card, with room for each fellow to own a country or region.",
  },
  {
    title: "Targeted outreach to potential funders",
    category: "Funding",
    region: "Global",
    effort: "40–100h",
    expertise: "Specialist",
    contact: "benjamin",
    blurb: "Research, prioritise and personally approach a shortlist of high-potential funders — major philanthropists and foundations — who could fund this work at a meaningfully larger scale.",
    skills: ["Fundraising", "Research", "Pitching", "Relationship-building"],
    detail: "Build a researched shortlist of high-net-worth donors and foundations — including the search for a major single funder — and approach them in a tailored, high-touch way. One yes can change the ceiling on everything else.",
  },
  {
    title: "Mass cold-outreach to potential funders",
    category: "Funding",
    region: "Global",
    effort: "30–60h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "Run a high-volume, systematic cold-outreach campaign across many potential funders to make landing support a numbers game.",
    skills: ["Cold outreach", "Research", "CRM / tracking", "Persistence"],
    detail: "Where targeted outreach goes deep on a shortlist, this goes wide: compile a large list of potential funders — foundations, donor networks, grant programmes — and run a systematic cold-outreach campaign at volume, so that securing funding becomes a numbers game rather than luck.",
  },
  {
    title: "“Conscientious objector” pledge for AI workers",
    category: "Outreach",
    region: "Global",
    effort: "40–80h",
    expertise: "Some experience",
    contact: "benjamin",
    blurb: "A public campaign inviting AI researchers to pledge not to work on frontier capability scaling.",
    skills: ["Campaigning", "Community-building", "Messaging", "Ethics"],
    detail: "Launch a public pledge inviting researchers to commit not to work on frontier capability scaling — echoing past 'trust your conscience / quit your job' movements. Norm-shifting if it catches, but easy to caricature, so framing matters.",
  },
  {
    title: "SitRep — polish & extend the daily AI-risk brief",
    category: "Capacity & Infrastructure",
    region: "Global",
    effort: "20–60h",
    expertise: "Specialist",
    contact: "matilda",
    blurb: "Improve SitRep: a daily Markdown brief, auto-generated at 03:00 UTC, filtering pause-relevant signal from curated sources.",
    skills: ["Python / automation", "NLP", "News curation", "Product sense"],
    detail: "SitRep already exists as a working prototype: a daily Markdown brief, auto-generated at 03:00 UTC, that filters pause-relevant signal from a curated set of sources and goes to a small distribution list. Help polish the rough edges, broaden the sources, and grow the distribution. Matilda da Rue currently maintains it.",
  },
];
